name: Check Doc Updates and Trigger Documentation Update

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

permissions:
  checks: write

jobs:
  check-secret:
    runs-on: ubuntu-latest
    outputs:
      has-token: ${{ steps.check.outputs.has-token }}
    steps:
      - id: check
        run: |
          if [ "${{ secrets.ORG_GITHUB_BOT_TOKEN }}" != "" ]; then
            echo "has-token=true" >> "$GITHUB_OUTPUT"
          else
            echo "has-token=false" >> "$GITHUB_OUTPUT"
          fi

  check-and-notify:
    needs: check-secret
    if: needs.check-secret.outputs.has-token == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check commits dates
        id: check-updates
        run: |
          # Get last commit date from current repo's doc branch
          DOC_RESPONSE=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/commits/doc")
          
          DOC_COMMIT_DATE=$(echo $DOC_RESPONSE | jq -r '.commit.author.date')
          DOC_COMMIT_TIME=$(date -d "$DOC_COMMIT_DATE" +%s)
          
          # Get last commit date from keypop-api-docs gh-pages branch
          DOCS_RESPONSE=$(curl -s \
            -H "Authorization: token ${{ secrets.ORG_GITHUB_BOT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/eclipse-keyple/keyple-api-docs/commits/gh-pages")
          
          DOCS_COMMIT_DATE=$(echo $DOCS_RESPONSE | jq -r '.commit.author.date')
          DOCS_COMMIT_TIME=$(date -d "$DOCS_COMMIT_DATE" +%s)
          
          # Compare dates
          if [ $DOC_COMMIT_TIME -gt $DOCS_COMMIT_TIME ]; then
            echo "Doc branch has newer changes"
            echo "Doc commit time: $(date -d @$DOC_COMMIT_TIME)"
            echo "Docs commit time: $(date -d @$DOCS_COMMIT_TIME)"
            echo "should-update=true" >> "$GITHUB_OUTPUT"
          else
            echo "No new changes to publish"
            echo "Doc commit time: $(date -d @$DOC_COMMIT_TIME)"
            echo "Docs commit time: $(date -d @$DOCS_COMMIT_TIME)"
            echo "should-update=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Repository Dispatch Event
        if: steps.check-updates.outputs.should-update == 'true'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ORG_GITHUB_BOT_TOKEN }}
          repository: eclipse-keyple/keyple-api-docs
          event-type: update-submodules